name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9

    - name: Install dependencies
      run: make install

    - name: Lint with Pylint
      run: make lint

    - name: Test with Pytest
      run: make test

    - name: Format code with Python Black
      run: make format
